Repository tedaky/memory-game, pull requests merged in 2020-12, with the labels that each got.

#19 Improve VS Code debugging
  .devcontainer/devcontainer.json
  .vscode/launch.json
Labels: development, enhancement

#21 Bengali translations
  projects/the-application/src/assets/i18n/high-scores/bn.json
  projects/the-application/src/assets/i18n/recent-scores/bn.json
  projects/the-application/src/assets/i18n/settings/bn.json
Labels: locale, new

#16 Update English main locale
  projects/the-application/src/assets/i18n/main/en.json
  projects/the-application/src/install/install.component.html
Labels: enhancement, locale

#14 tranlated main and game
  projects/the-application/src/assets/i18n/game/bn.json
  projects/the-application/src/assets/i18n/main/bn.json
Labels: locale, new

#29 Create the stopwatch worker
  projects/the-application/src/game/game.component.ts
  projects/the-application/src/game/game.module.ts
  projects/the-application/src/stopwatch/stopwatch.component.html
  projects/the-application/src/stopwatch/stopwatch.component.ts
  projects/the-application/src/stopwatch/stopwatch.service.ts
  projects/the-application/src/stopwatch/worker/post.ts
  projects/the-application/src/stopwatch/worker/stopwatch.ts
  projects/the-application/src/stopwatch/worker/stopwatch.worker.ts
  projects/the-application/src/time/time.d.ts
Labels: enhancement, new

#30 Fixup cards worker
  projects/the-application/src/cards/cards.service.ts
  projects/the-application/src/cards/worker/cards.ts
  projects/the-application/src/cards/worker/post.ts
Labels: enhancement

#33 Create language section
  projects/the-application/src/language/language.service.ts
  projects/the-application/src/settings/settings.component.html
  projects/the-application/src/settings/settings.component.ts
Labels: enhancement, locale, new

#35 set meta and index
  projects/the-application/src/assets/i18n/game/de.json
  projects/the-application/src/assets/i18n/game/es.json
  projects/the-application/src/assets/i18n/high-scores/de.json
  projects/the-application/src/assets/i18n/high-scores/es.json
  projects/the-application/src/assets/i18n/main/de.json
  projects/the-application/src/assets/i18n/main/es.json
  projects/the-application/src/assets/i18n/recent-scores/de.json
  projects/the-application/src/assets/i18n/recent-scores/es.json
  projects/the-application/src/assets/i18n/settings/de.json
  projects/the-application/src/assets/i18n/settings/es.json
  projects/the-application/src/index.bn.html
  projects/the-application/src/index.en.html
  projects/the-application/src/manifest.bn.webmanifest
  projects/the-application/src/manifest.de.webmanifest
  projects/the-application/src/manifest.en.webmanifest
  projects/the-application/src/manifest.es.webmanifest
  projects/the-application/src/manifest.hi.webmanifest
  projects/the-application/src/manifest.webmanifest
Labels: release

#20 telugu translation added
  projects/the-application/src/assets/i18n/game/te.json
  projects/the-application/src/assets/i18n/high-scores/te.json
  projects/the-application/src/assets/i18n/main/te.json
  projects/the-application/src/assets/i18n/recent-scores/te.json
  projects/the-application/src/assets/i18n/settings/te.json
Labels: locale, new

#40 Create linear gradient background
  projects/the-application/src/game/game.component.scss
  projects/the-application/src/main-menu/main-menu.component.scss
  projects/the-application/src/root/root.component.scss
  projects/the-application/src/score/score-template.component.scss
  projects/the-application/src/settings/settings.component.scss
  projects/the-application/src/stopwatch/stopwatch.component.html
Labels: enhancement

#26 Hindi Translation
  projects/the-application/src/assets/i18n/game/hi.json
  projects/the-application/src/assets/i18n/high-scores/hi.json
  projects/the-application/src/assets/i18n/main/hi.json
  projects/the-application/src/assets/i18n/recent-scores/hi.json
  projects/the-application/src/assets/i18n/settings/hi.json
Labels: locale, new

#38 Kannada translation
  projects/the-application/src/assets/i18n/game/kn.json
  projects/the-application/src/assets/i18n/high-scores/kn.json
  projects/the-application/src/assets/i18n/main/kn.json
  projects/the-application/src/assets/i18n/recent-scores/kn.json
  projects/the-application/src/assets/i18n/settings/kn.json
Labels: locale, new

#44 Add language to selection
  angular.json
  projects/the-application/src/index.hi.html
  projects/the-application/src/index.kn.html
  projects/the-application/src/index.te.html
  projects/the-application/src/language/language.service.ts
  projects/the-application/src/manifest.hi.webmanifest
  projects/the-application/src/manifest.kn.webmanifest
  projects/the-application/src/manifest.te.webmanifest
  projects/the-application/src/root/root.module.ts
Labels: locale, new
